### ISSUE TITLE
E5550 gets stuck before installer

### ISSUE THREAD

**Issue by DedFishy** [SkyrilHD/Dell-Exx50-Hackintosh#80]
Hey, I'm trying to install MacOS Monterey on my E5550, and I'm having a weird problem. When I load my installer file (labeled "NO NAME (dmg)"), I have a blank screen, then some text, then a lot of text, and then nothing. I can't get to the installer.
I've tried:
- Building a USB Kext and OC Snapshotting my plist 
- Installing different versions of MacOS (Sonoma, Big Sur, etc.) to the same result
- Activating verbose mode (before all I got was a frozen Apple logo and progress bar partially loaded
- Resetting BIOS and changing everything to recommended settings
- Added -igfxmlr argument (see last photo)

Any ideas? I know you (the owner of this repository) aren't really in this space as much anymore but I feel like this is something blatantly obvious and shortsighted on my end.
Thanks!

# Photos:

## Boot selection:
![image](https://github.com/user-attachments/assets/11a35b43-4b6f-4df6-b125-905e7e2d1e1a)

## First text that stays up for a while:
![image](https://github.com/user-attachments/assets/8270a4ae-0bef-4a1d-ae6e-7c3c52edf356)

## Where it freezes (does the IOConsoleUsers gIOScreenLockState have something to do with it?)
![image](https://github.com/user-attachments/assets/7d3e0627-dc87-492a-8003-a53ff531f2fc)

**Comment by SkyrilHD** [comment]
`IOConsoleUsers gIOScreenLockState` means that you are almost done booting, but macOS cannot exit verbose mode to switch to userspace.

If I recall correctly, the E5550 come with either a Haswell (4th gen) or Broadwell (5th gen) Intel processor. This repo _only_ supports the Broadwell variants, so make sure your device isn't the Haswell one. If it is (which it most likely is, based on the information I have), the only thing you need to do is change the platform-id of the iGPU. You can find recommended platform-ids in the Dortania guide. After that, macOS should (hopefully) boot just fine.

**Comment by SkyrilHD** [comment]
I see your BIOS version is very old. Try updating it to the latest version.

Since Broadwell is natively supported on Monterey, the EFI should work without any changes.

**Comment by DedFishy** [comment]
Thanks for the suggestion! I realized that my battery was completely shot so I had to load up a USB drive with DOS to force the update to go through since it didn't like only having AC power, but I've installed BIOS version A24 successfully. I still have the exact same problem happen, though. It also looks like my BIOS settings have stayed at the recommended settings through the update. Any ideas?

Updated BIOS:
![image](https://github.com/user-attachments/assets/06e18dfe-bb37-4f76-b3e5-af8e4a019cb8)

**Comment by SkyrilHD** [comment]
Can you disable the GPU acceleration with this boot-arg: `-igfxvesa`. Let's see if the issue is with the GPU.

Additionally, if you have any Intel Wi-Fi kexts enabled, turn them off.

Also, looking at your original post, I see a lot of `busy timeout, (240s): 'MacBookPro12,1'` I had this issue when I had a faulty USBMap, but I fixed that a long time ago. I have no idea why this happens.

How did you download the installer? Is it an online installer? If yes, is it possible to create an offline installer?

**Comment by DedFishy** [comment]
Hey, sorry, I would have replied sooner but my computer takes around 5-10 minutes to finish showing all the text from the console.

1: My boot args are now `-wegnoegpu -v -igfxvesa` (wegnoegpu was already there), but I still get the same result as before unfortunately.

2: The only WiFi or Intel Kexts I see are Airportltlwm, Intel Bluetooth, and Intel LAN (Mausi). I haven't touched them because I don't think those are what you're referring to, but if you meant to disable airportltlwm then that's my bad. With my current situation I won't necessarily need WiFi, so if that ends up being the issue I can live without it.

3: With the busy timeout, I get a lot of those messages. I actually did map my USBs and put the file in my Kexts, but I can't say for sure that I did it correctly.

4: To get the installer I used the Python script that came with OpenCore. It gave me BaseSystem.x files that I put on my drive, which I assume is the offline installer. Either way, I also have access to ethernet if needed.

5: I've also been resetting NVRAM whenever I make changes.

Thanks!

**Comment by SkyrilHD** [comment]
1. So it is not the iGPU (?)
2. My goal is to mitigate causal problems which a lot of issues I had in the past related to Intel Wi-Fi kexts
3. Is there any guide you followed? (Do not confuse USBMap with UTBMap, these are two different files!)
4. The online installer is ~500-800 MB, which only contains the recovery environment. An offline installer is larger than 12GB, you can (AFAIK) only create an offline installer with macOS. So what I mean by “is it possible to create an offline installer?” is whether you have access to any macOS system to create the full installer.

I will try the same steps you did on my E7250 and will report back:
- Downloading v4.0 (Monterey) EFI
- Creating a USB thumb drive with BaseSystem files and the EFI (untouched)
- Booting to the Recovery installer

If I missed any steps, please let me know.

**Comment by DedFishy** [comment]
To make my map I think I found some random Reddit tutorial or something along those lines. Looking at my files, it looks like I actually made a UTBMap, which I didn't know was different. Should I try making a USBMap instead?

Yeah, it seems I do have an online installer. I don't have immediate access to a Mac, and even if I did, I only have two USB drives. A 4GB USB that I'm using for this that won't fit a full install, and a 64GB USB that I can't use because this laptop won't boot a UEFI formatted drive from Rufus, diskpart is the only way to make a legacy bootable drive on Windows (according to the tutorial), and diskpart won't format a USB that large to FAT32. That said, if a full offline Mac OS installer would be almost guaranteed to work, I could find a way to get a real Mac and buy a decent 16GB USB drive.


Your steps seem good, except for that I did actually mess a bit with the EFI in two ways. I added -v to the boot options in the plist to see logs, and I added the UTB kext and used ProperTree to OC Snapshot the EFI afterward. I may have done that incorrectly, but I also seem to have done the mapping incorrectly in the first place.

Thanks again!

**Comment by SkyrilHD** [comment]
I think this explains the `busy timeout, (240s): 'MacBookPro12,1'` issue.

I tried booting the Monterey Online installer on my E7250 with the aforementioned steps (however, I did add -v though, in case it would get stuck) and it works. I suggest you try the same. 

![IMG_F9AD9237B2C5-1](https://github.com/user-attachments/assets/0e0b9ad2-c7ed-4354-a319-7e23c88f6f86)

**Comment by DedFishy** [comment]
I appreciate the effort you're putting into this by making a USB to test. Thank you so much!

Alright, I'll list the exact steps I'm taking here as I take them, sorry if it's a bit verbose:
- Using OpenCore 1.0.1 debug, run the command `py macrecovery.py -b Mac-FFE5EF870D7BA81A -m 00000000000000000 download` to download the installer for Mac OS Monterey.
- Meanwhile, use diskpart to format the drive as FAT32 GPT with one partition
- Copy the whole com.apple.recovery.boot folder from OpenCore to my freshly formatted USB drive
- Download the latest Monterey EFI from the GitHub releases: "Dell-Exx50-Hackintosh-4.0.Monterey.zip"
- Copy the EFI folder to the root of my USB drive
- Using ProperTree, change the boot arguments to include -v for debugging
- Eject my USB drive from Windows and move it to my E5550
- Turn on the laptop and spam F12 to load the one-time boot menu
- Fix my boot settings because part of the ID of the drive was changed with the reformat and it couldn't find the BOOTX64.efi file anymore (not the actual path to the file though)
- Side note: I assume that BOOTX64.efi is the correct file to be booting, but if I'm wrong then please correct me
- Hit space and Reset NVRAM
- Hit space and select No Name (dmg)
- After about 15 minutes, I get the same result

If there's anything I messed up there, please let me know.

Thanks!

**Comment by DedFishy** [comment]
Oh, I figured out that I actually can boot from my 64GB usb, and i just hadn't set up the path to the EFI. It also has USB 3.0 and it's booting right now, but so far it's doing the same thing except perhaps a bit faster. I'll update this if that somehow fixes it.

**Comment by SkyrilHD** [comment]
I followed essentially the same steps as you, the main differences are that I used Disk Utility (included with macOS) and instead of booting BOOTX64.efi, I booted OpenCore.efi.

Is the `busy timeout, (240s): 'MacBookPro12,1'` issue resolved?

You could also try toggling 'Enable Legacy Option ROMs' in the BIOS (General>Advanced Boot Options). Mine is currently disabled. However, needed on 1080p models.

**Comment by DedFishy** [comment]
I'm now trying to boot OpenCore.efi just to see if there's a difference, but so far it's doing the same thing and I don't want to wait so long for the same thing to happen again.

I still am getting the `busy timeout, (240s): 'MacBookPro12,1'`, and so far I've never not gotten it.
"Enable Legacy Option ROMs" always failed to boot the USB for me, which is why I'm using UEFI to load the EFI files directly.

I don't see any reason our models should be different enough to fail like this.
Thanks for the reply!

**Comment by DedFishy** [comment]
By the way, same result when I boot OpenCore.efi, as expected.

**Comment by SkyrilHD** [comment]
Yeah, sorry, I am slowly hitting on a dead end. It's been a while since I did anything hackintosh-related on this laptop. (Also I am very tired xD)

Checked the previous issues with the same laptop model:

This person mentions that it stuck on the Apple logo (same as yours, basically). However, few days later he got it working: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/issues/73

This person got it fixed by resetting NVRAM and BIOS settings: https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/issues/70

This person got it fixed by using an older version of the EFI(?): https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/issues/36

Can you try an older version, like [v2.9](https://github.com/SkyrilHD/Dell-Exx50-Hackintosh/tree/v2.9)?

**Comment by DedFishy** [comment]
I don't blame you for hitting a dead end, this makes no sense to me either.
I've loaded v2.9 and it did not work, it just did the same thing.
The last things I'll try are 2.0 and another BIOS reset, maybe I missed a setting when I updated?
Other than that, thanks so much for the support! Even if I can't get MacOS started, you've done more than enough to help me out.

**Comment by DedFishy** [comment]
Hey, just wanted to let you know that I found a different computer and successfully got MacOS Sonoma running on it, so I no longer need to get this setup to work. If you'd like to close this issue as wontfix or something that's fine, because it seems I have an edge case. The laptop I have was originally from some other company, so it may have some weird properties.
Thanks again for all the help!

**Comment by SkyrilHD** [comment]
I will close this issue since you have a different computer.

Anyone who has this issue can post here. Even though it is impossible for me to reproduce this issue, I will do my best to resolve it.
